### ISSUE TITLE
bidi implementation incomplete????

### ISSUE THREAD

**Issue by d3aWrVVmn** [firedm/FireDM#243]
when updating from 2021.4.8 version using the built-in update tool, got this error

---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\Python\Python38-32\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python\Python38-32\lib\site-packages\cx_Freeze\initscripts\Console.py", line 33, in run
  File "D:\python\myProgects\FireDM\firedm.py", line 11, in <module>
  File "D:\FireDM\temp_firedm\extracted\firedm\FireDM.py", line 31, in <module>
  File "D:\FireDM\temp_firedm\extracted\firedm\controller.py", line 26, in <module>
  File "D:\FireDM\temp_firedm\extracted\firedm\setting.py", line 15, in <module>
  File "D:\FireDM\temp_firedm\extracted\firedm\downloaditem.py", line 19, in <module>
AttributeError: module 'awesometkinter' has no attribute 'render_bidi_text'

---------------------------
OK   
---------------------------

when downloading the binary from https://github.com/firedm/FireDM/releases/tag/2021.5.22 got this error

---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\Python\Python38-32\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python\Python38-32\lib\site-packages\cx_Freeze\initscripts\Console.py", line 33, in run
  File "D:\python\myProgects\FireDM\firedm.py", line 11, in <module>
  File "D:\FireDM\lib\firedm\FireDM.py", line 31, in <module>
    from .controller import Controller, set_option
  File "D:\FireDM\lib\firedm\controller.py", line 26, in <module>
    from . import setting
  File "D:\FireDM\lib\firedm\setting.py", line 15, in <module>
    from . import downloaditem
  File "D:\FireDM\lib\firedm\downloaditem.py", line 18, in <module>
    import awesometkinter as atk
  File "D:\FireDM\lib\awesometkinter\__init__.py", line 21, in <module>
    from .bidi import *
  File "D:\FireDM\lib\awesometkinter\bidi.py", line 12, in <module>
    import pyfribidi
ModuleNotFoundError: No module named 'pyfribidi'

---------------------------
OK   
---------------------------

running windows 10 x64

**Comment by firedm** [comment]
@d3aWrVVmn 
Thanks for reporting, will work on a fix for it

**Comment by nero-0** [comment]
Same error here

**Comment by firedm** [comment]
@d3aWrVVmn  
@nero-0 
please test latest release and see if problem solved  https://github.com/firedm/FireDM/releases/latest

**Comment by nero-0** [comment]
@firedm 
Now it's working for me, thanks!

**Comment by firedm** [comment]
@nero-0 
great! :+1:
